/* Generated By:JavaCC: Do not edit this line. JSONParserConstants.java */
package tech.glacial.json.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int JNull = 1;
    /**
     * RegularExpression Id.
     */
    int True = 2;
    /**
     * RegularExpression Id.
     */
    int False = 3;
    /**
     * RegularExpression Id.
     */
    int Spaces = 4;
    /**
     * RegularExpression Id.
     */
    int JNumber = 5;
    /**
     * RegularExpression Id.
     */
    int JString = 10;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
        "<EOF>",
        "\"null\"",
        "\"true\"",
        "\"false\"",
        "<Spaces>",
        "<JNumber>",
        "\"\\\"\"",
        "<token of kind 7>",
        "<token of kind 8>",
        "<token of kind 9>",
        "\"\\\"\"",
        "\"[\"",
        "\",\"",
        "\"]\"",
        "\"{\"",
        "\":\"",
        "\"}\"",
    };

}
